version: "3.9"

services:
  
  database:
    container_name: postgresql_db
    image: postgres:14.5
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports: 
      - 5432:5432

  
volumes:
  postgres_data: